### ISSUE TITLE
Skipping seasonal adjustment in proc_index

### ISSUE THREAD

**Issue by Leksa2** [trendecon/trendecon#82] opened 2022-07-21 22:23 UTC
Hi, 

It seems like the proc_index function has a problem converting geo= "" 
keywords (whole world) due to an error "holidays for the geo not found" or something similar,
when the proc_index tries to make seasonal adjustments.

is it possible to skip the seasonal adjustment when having the whole world or a specific country 
as the geo argument?  I would need unadjusted series anyways.

Best, Leo

**Comment by karoliskoncevicius** [comment] 2022-07-23 17:52
Hello, thank you for reporting,

This indeed doesn't work, currently seasonal adjustment is done with the help of R package `prophet` and it requires a single specific country. So the error you got stated that holiday days for the country named "" (empty string) is not supported.

I added a check to skip seasonal adjustment in such cases, currently awaiting internal review at the pull request #83 

Will be included in master once and if it passes our reviews.

**Comment by karoliskoncevicius** [comment] 2022-07-23 18:47
Pull request #83 is now merge and live in the master branch. Update the `trendecon` package and seasonal adjustment should be skipped for `geo=""`.

Closing this issue now, but if the issues persists please reopen.

**Comment by Leksa2** [comment] 2022-07-25 06:32
The code ran into an error. I reinstalled trendecon and the related packages.

It now reports a missing file that the code itself should write:

*updating keywords*
Error: 'PATH\FirstKeyword_sa.csv' does not exist.

**Comment by karoliskoncevicius** [comment] 2022-07-25 08:49
Ah I see, since we skipped the sa step, the file "_sa" is no longer there.

@christophsax - we have a small problem now: pipeline wants to have 'keyword_sa.csv' file, however when I skipped seasonal adjustment for `geo=''` the file is no longer there. As far as I see we have to ways of going about it:

1. Write data under 'keyword_sa.csv', even when seasonal adjustment is skipped.
2. Make the pipeline read data from a different place, conditioning on `geo=''`

Maybe you will have a comment which of these looks more suitable?

**Comment by christophsax** [comment] 2022-07-25 08:52
Or go back and do a seasonal adjustment without working days if `geo=""`?

That would yield proper, seasonal adjusted values for `geo=""` as well.

**Comment by Leksa2** [comment] 2022-07-25 20:57
Noting here that I'm looking for the possibility to create an index that is not seasonally adjusted, both geo="" and specific countries (I'm trying to create a counterfactual to ad boosted sales for the purpose of studying ad ROI). Therefore, the solution proposed by Christoph likely won't serve this purpose.

If this bug fix won't extend to skipping seasonal adjustment for geo = country, is there a possibility for me to trace the related functions and modify them in order to make this happen? Any help is much appreciated.

**Comment by karoliskoncevicius** [comment] 2022-07-26 19:09
@Leksa2 I see your issue but I am thinking about what behaviour you are after. It seems like you want to turn off seasonal adjustment, but still have the data written under "keyword_sa.csv" as per your previous comment? I think this would introduce some confusion to the package, so I agree with Christoph's solution as default behaviour.

Regarding your needs - I can add an additional parameter "seas_adjust = FALSE" to the proc_keyword function, but the data would in that case not be under "keyword_sa.csv". So not sure how to satisfy your needs here, without introducing inconsistencies.

Currently, if you want, you can do everything manually, as per our [vignette](https://trendecon.github.io/trendecon/articles/daily-series.html).

`proc_keyword()` function in essence simply does the following:

    proc_keyword_latest(keyword = keyword, geo = geo, n_windows = n_windows)
    proc_combine_freq(keyword = keyword, geo = geo)
    proc_seas_adj(keyword = keyword, geo = geo)

These functions are not exported, but you can reach them via `trendecon:::`. So for example instead of calling:

    proc_keyword("keyword", geo="")

You would call:

    trendecon:::proc_keyword_latest("keyword", geo="", n_windows=2)
    trendecon:::proc_combine_freq("keyword", geo="")

And then skip the last `proc_seas_adj()` step. But ideally I would understand your needs better and implement a possible solution, given we can come up with some compromise with regards to where to put unadjusted data.

**Comment by Leksa2** [comment] 2022-07-27 08:36
Thanks Karolis!

Basically what I'm trying to do is create indexes ('DE', 'US', 'FR',..., "") that are not seasonally adjusted (-->based on keywords that are not sa). 

So the proc_index() function first combines daily, weekly and monthly keyword data into intermediate _sa and _mwd files. So i guess the solution here would be to make the function have an option to create the index from _mwd files instead of _sa files. (i dont need the data to be written in a specific file e.g. _sa. Only the end result of an unadjusted index matters). I think this could work with geo <>"" ?

What comes to geo="", maybe the created _sa file could be seasonally adjusted without working days as Christoph mentioned, while still having the option of using _mwd files to combine the index?

Thanks for bringing up the trendecon::: functions, I'll try them in the meanwhile!

**Comment by Leksa2** [comment] 2022-08-09 13:37
Update: didn't manage to create indexes with the trendecon::: funtions - i got the "error in prcomp.default(x, scale = TRUE, ...) : cannot rescale a constant/zero column to unit variance". It's likely that i made some mistake.

However, I traced the proc_index() and simply changed the "suffix" argument within the read_keywords() from "sa" to "mwd" and that seems to do the trick.

**Comment by karoliskoncevicius** [comment] 2022-10-08 14:35
Hello @Leksa2 , just now remembered that this issue was still left unfinished.

The original issue for the error is now resolved by skipping the holiday-adjustment step for unsupported geo ids, as implemented in #87 

Regarding your workflow - I think this is the case where using the singular functions one by one makes more sense.

`trendecon` package has several functions that do everything alone, and, in addition, it has a wrapper function which combines the stand-alone functions in tandem to produce data that went through the proposed pipeline. I feel, that the correct direction for people who want to deviate from this pipeline is to use those stand-alone functions one by one, or to create their own customised wrapper functions, instead of expanding the wrapper function present in `trendecon`

Pinging @christophsax to see if he agrees with me.

**Comment by christophsax** [comment] 2022-10-08 14:38
Yes, trendecon was designed with a relatively specific workflow in mind. As it wraps the CRAN package [gtrendsR](https://cran.r-project.org/package=gtrendsR), you may want to use it directly, and implement your specific workflow.

**Comment by karoliskoncevicius** [comment] 2022-10-08 14:53
Thanks @christophsax .

PR is merged, closing. The discussion can continue if needed; either here - or in a separate dedicated issue.

**Closed by karoliskoncevicius** 2022-10-08 14:53 UTC
Labels: bug
