### ISSUE TITLE
Countrycode for the 'whole world'

### ISSUE THREAD

**Issue by Leksa2** [trendecon/trendecon#78] opened 2022-07-03 19:22 UTC
Hi there,

First of all, many thanks for creating the trendecon package. It has brought immense value to me by providing supplementary data for my thesis!

Furthermore, I have a question regarding the code argument "country". Is there any chance to create a series including the trend for "the whole world"? At least Google trends provides the option. If I understand correctly, leaving the country argument blank would produce a time-series "CH" as the country?

Thanks in advance!
Leo

**Comment by christophsax** [comment] 2022-07-03 20:55
@karoliskoncevicius, thanks for having a look.

**Comment by karoliskoncevicius** [comment] 2022-07-08 09:39
Closing this now, but please comment and reopen if `geo=""` does not work as intended.

**Closed by karoliskoncevicius** 2022-07-08 09:39 UTC
Labels: meta

**Comment by Leksa2** [comment] 2022-07-14 07:28
Thanks! this seems to be working also for proc_keyword_init().
