### ISSUE TITLE
401 Error after just a handful of searches

### ISSUE THREAD

**Issue by wes3985** [trendecon/trendecon#73] opened 2022-05-23 10:29 UTC
After my 10th Keyword search over ~2 weeks the code no longer runs and is returning a 401 error, I slightly suspect that google may have blocked me however given how infrequently I'm using it (literally just 10 times over 2 weeks) this is a bit surprising. The webpage still works in a browser as well which is a bit inconsistent with google blocking me. Here is my code:

```
library(trendecon)
keyword<-"hotels"
data_consistent <- ts_gtrends_mwd(c(keyword))
write.csv(data_consistent, paste("raw_data/tradeecon_", keyword, ".csv", sep=""), row.names=FALSE)
```

And I am getting the following error:

```
Downloading data for 2006-01-01 2006-07-01
Error: Problem with `mutate()` column `trend_data`.
i `trend_data = list(...)`.
x Status code was not 200. Returned status code:401
i The error occurred in row 1.
Run `rlang::last_error()` to see where the error occurred.
> rlang::last_error()
<error/dplyr:::mutate_error>
Problem with `mutate()` column `trend_data`.
i `trend_data = list(...)`.
x Status code was not 200. Returned status code:401
i The error occurred in row 1.
Backtrace:
  1. trendecon::ts_gtrends_mwd(c(keyword))
 11. trendecon::ts_gtrends(...)
 13. base::lapply(...)
 14. trendecon:::FUN(X[[i]], ...)
 15. trendecon:::gtrends_with_backoff(...)
Run `rlang::last_trace()` to see the full context.
> rlang::last_trace()
<error/dplyr:::mutate_error>
Problem with `mutate()` column `trend_data`.
i `trend_data = list(...)`.
x Status code was not 200. Returned status code:401
i The error occurred in row 1.
Backtrace:
     x
  1. +-trendecon::ts_gtrends_mwd(c(keyword))
  2. | \-trendecon:::ts_gtrends_windows(...)
  3. |   \-`%>%`(...)
  4. +-dplyr::ungroup(.)
  5. +-tidyr::unnest(., cols = trend_data)
  6. +-dplyr::mutate(...)
  7. +-dplyr:::mutate.data.frame(...)
  8. | \-dplyr:::mutate_cols(.data, ..., caller_env = caller_env())
  9. |   +-base::withCallingHandlers(...)
 10. |   \-mask$eval_all_mutate(quo)
 11. \-trendecon::ts_gtrends(...)
 12.   +-stats::setNames(...)
 13.   \-base::lapply(...)
 14.     \-trendecon:::FUN(X[[i]], ...)
 15.       \-trendecon:::gtrends_with_backoff(...)
<error/simpleError>
Status code was not 200. Returned status code:401
```

**Comment by wes3985** [comment] 2022-05-23 10:48
```
sessioninfo()
platform       x86_64-w64-mingw32               
arch           x86_64                           
os             mingw32                          
crt            ucrt                             
system         x86_64, mingw32                  
status                                          
major          4                                
minor          2.0                              
year           2022                             
month          04                               
day            22                               
svn rev        82229                            
language       R                                
version.string R version 4.2.0 (2022-04-22 ucrt)
```

**Comment by karoliskoncevicius** [comment] 2022-06-06 10:54
I can reproduce the error, looking at it now, will update soon

**Comment by karoliskoncevicius** [comment] 2022-06-06 11:27
The issue is likely caused by some other package and is fixed in a newer version.

I didn't track which, but the error disappeared after `update.packages(ask=FALSE)`:

```r
> library(trendecon)
> keyword<-"hotels"
> data_consistent <- ts_gtrends_mwd(c(keyword))
Downloading data for 2006-01-01 2006-07-01
Downloading data for 2006-01-16 2006-07-16
Downloading data for 2006-01-31 2006-07-31
Downloading data for 2006-02-15 2006-08-15
Downloading data for 2006-03-02 2006-09-02
Downloading data for 2006-03-17 2006-09-17
Downloading data for 2006-04-01 2006-10-01
Downloading data for 2006-04-16 2006-10-16
Downloading data for 2006-05-01 2006-11-01
Downloading data for 2006-05-16 2006-11-16
Downloading data for 2006-05-31 2006-12-01
Downloading data for 2006-06-15 2006-12-15
Downloading data for 2006-06-30 2006-12-30
Downloading data for 2006-07-15 2007-01-15
Downloading data for 2006-07-30 2007-01-30
Downloading data for 2006-08-14 2007-02-14
Downloading data for 2006-08-29 2007-03-01
Downloading data for 2006-09-13 2007-03-13
Downloading data for 2006-09-28 2007-03-28
Downloading data for 2006-10-13 2007-04-13
```

If you are using macOS and recently updated be sure to also upgrade the clang compiler to 14 version. For me some packages refused to update but all started working with the newest clang.

**Comment by karoliskoncevicius** [comment] 2022-06-06 11:28
Changed the tag to "meta" since this is not a bug in `trendecon`. Closing now, but please comment or reopen if it persists.

**Closed by karoliskoncevicius** 2022-06-06 11:28 UTC
Labels: meta
