### ISSUE TITLE
Error: Cannot parse the supplied time format.

### ISSUE THREAD

**Issue by tasfiq13** [trendecon/trendecon#96] opened 2023-02-25 20:12 UTC
1. its showing error in my mac fo the command proc_keyword_init: "Error: Cannot parse the supplied time format." but it works fine in windows. Please see this and try to implement tz=0 https://github.com/PMassicotte/gtrendsR/issues/322.
2.  many functions are not loaded (i.e., path_utils.R, proc_combine_freq.R, proc_seas_adj.R) thats why proc_combine_freq is not working. 

Please make an update to fix the issues.

**Comment by karoliskoncevicius** [comment] 2023-02-25 20:20
Hello @tasfiq13 and thank you for opening an issue.

In order to get to the bottom of the raised issues and help you I will have to ask some questions:

1. Can you provide the full command of `proc_keyword_init()` that results in an error on your mac?
2. Are all your packages up to date? (you can update them all with `update.packages(ask = FALSE)`
3. Can you share the code for what you doing which requires `path_utils.R` and `proc_combine_freq.R` to be exported?

**Comment by tasfiq13** [comment] 2023-02-25 20:28
Thanks for your quick response.

1. proc_keyword_init("crypto", geo = "", from = "2004-01-01") this the code.
2. not updated. I will try to update
3. proc_combine_freq("crypto", geo = "") this the code.

**Comment by karoliskoncevicius** [comment] 2023-02-25 20:43
Thanks.

At the moment I am updating all the packages as well and will check how your line behaves on a Mac.

Regarding `proc_combine_freq()` - not sure why you are running this. The usual approach is to call `proc_keyword()` instead, which will then download the latest data, combine it with the existing data, and then run `proc_combine_freq()` plus `proc_seas_adj()`. So I am curious what are you trying to accomplish - do you want to skip the seasonal adjustment step?

**Comment by tasfiq13** [comment] 2023-02-25 20:51
the `proc_keyword()` give me daily, weekly and monthly data. then I want to use proc_combine_freq() to combine the frequency. after that I will run proc_seas_adj() to adjust the frequency.

**Comment by karoliskoncevicius** [comment] 2023-02-25 20:52
@tasfiq13 this is not correct. Note that there are two separate functions: `proc_keyword_init()` and `proc_keyword()`.

The first one has to be run when you are downloading the data for the first time. It gives you daily, weekly, and monthly data.
The second function can then be run in order to combine daily, weekly, and monthly data and do seasonal adjustment.

**Comment by karoliskoncevicius** [comment] 2023-02-25 20:55
Here are the relevant lines in the `proc_keyword()` function, that execute the un-exported functions for combining frequencies and doing seasonal adjustment: https://github.com/trendecon/trendecon/blob/master/R/proc_keyword.R#L31

**Comment by tasfiq13** [comment] 2023-02-25 20:57
Thanks I will try to follow your instruction.

About the mac issue. I have updated all packages and re-installed `trendecon` and the error is same as before :

```
Error in `mutate()`:
ℹ In argument: `trend_data = list(...)`.
ℹ In row 1.
Caused by error:
! Cannot parse the supplied time format.
```

**Comment by karoliskoncevicius** [comment] 2023-02-25 21:00
@tasfiq13 OK that is weird. I am on a mac, and I ran your code and it was executed without errors (finished just now).

Can you start R, load the trendecon package with `library(trendecon)` and call `sessionInfo()` and show it to me?

Here is mine:

    :: R
    > library(trendecon)
    > sessionInfo()
    R version 4.2.2 (2022-10-31)
    Platform: x86_64-apple-darwin22.1.0 (64-bit)
    Running under: macOS Ventura 13.2.1

    Matrix products: default
    BLAS:   /opt/local/Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libRblas.dylib
    LAPACK: /opt/local/Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libRlapack.dylib

    locale:
    [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

    attached base packages:
    [1] stats     graphics  grDevices utils     datasets  methods   base

    other attached packages:
    [1] trendecon_0.2.7

    loaded via a namespace (and not attached):
     [1] Rcpp_1.0.10       tsbox_0.3.1       magrittr_2.0.3    hms_1.1.2         tidyselect_1.2.0  munsell_0.5.0     anytime_0.3.9     colorspace_2.1-0  R6_2.5.1          rlang_1.0.6       fansi_1.0.4       dplyr_1.1.0
    [13] grid_4.2.2        data.table_1.14.8 gtable_0.3.1      utf8_1.2.3        cli_3.6.0         ellipsis_0.3.2    tibble_3.1.8      lifecycle_1.0.3   purrr_1.0.1       readr_2.1.4       gtrendsR_1.5.1    ggplot2_3.4.1
    [25] tzdb_0.3.0        tidyr_1.3.0       vctrs_0.5.2       glue_1.6.2        compiler_4.2.2    pillar_1.8.1      generics_0.1.3    scales_1.2.1      pkgconfig_2.0.3   tempdisagg_1.0

**Comment by tasfiq13** [comment] 2023-02-25 21:02
Please see the follows:
```
> library(trendecon)
> sessionInfo()
R version 4.2.1 (2022-06-23)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Monterey 12.5.1

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] trendecon_0.2.7

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.10        pillar_1.8.1       compiler_4.2.1     gtrendsR_1.5.1     remotes_2.4.2      tools_4.2.1        lifecycle_1.0.3    tibble_3.1.8      
 [9] gtable_0.3.1       anytime_0.3.9      pkgconfig_2.0.3    rlang_1.0.6        tsbox_0.3.1        cli_3.6.0          rstudioapi_0.14    dplyr_1.1.0       
[17] generics_0.1.3     vctrs_0.5.2        fs_1.6.1           hms_1.1.2          grid_4.2.1         tidyselect_1.2.0   glue_1.6.2         data.table_1.14.8 
[25] R6_2.5.1           fansi_1.0.4        purrr_1.0.1        tzdb_0.3.0         readr_2.1.4        ggplot2_3.4.1      tidyr_1.3.0        magrittr_2.0.3    
[33] scales_1.2.1       codetools_0.2-19   ellipsis_0.3.2     prophet_1.0        colorspace_2.1-0   tempdisagg_1.0     utf8_1.2.3         RcppParallel_5.1.6
[41] munsell_0.5.0   
```

**Comment by karoliskoncevicius** [comment] 2023-02-25 21:08
OK all your packages seem to be up to date. The only thing I could suspect is the older version of MacOS.

Can you try to run the following?:

    library(gtrends)
    gtrends("crypto", time = "2004-01-01 2019-11-30")

To see if this produces the same error?

**Comment by tasfiq13** [comment] 2023-02-25 21:11
No it runs smoothly.

**Comment by karoliskoncevicius** [comment] 2023-02-25 21:14
Interesting. Can you restart R and try this one again?:

    proc_keyword_init("crypto", geo = "", from = "2004-01-01")

If it still shows you an error - at which stage does the error occur? Right after calling the function, or do some results get downloaded?

**Comment by karoliskoncevicius** [comment] 2023-02-25 21:16
Just to confirm: works nicely on my end (screenshot):

![Screenshot](https://user-images.githubusercontent.com/7273684/221379969-0f229720-730d-44b5-b098-57978fb1b2cb.png)

**Comment by tasfiq13** [comment] 2023-02-25 21:20
It shows error after downloading all daily data and stuck before downloading weekly.

```
Downloading data for 2022-05-19 2022-11-19
Downloading data for 2022-06-03 2022-12-03
Downloading data for 2022-06-18 2022-12-18
Downloading data for 2022-07-03 2023-01-03
Downloading data for 2022-07-18 2023-01-18
Downloading data for 2022-08-02 2023-02-02
Downloading data for 2022-08-17 2023-02-17
Downloading data for 2022-09-01 2023-02-26
Error in `mutate()`:
ℹ In argument: `trend_data = list(...)`.
ℹ In row 212.
Caused by error:
! Cannot parse the supplied time format.
Run `rlang::last_error()` to see where the error occurred.
```
The result of `rlang::last_error()`

```
> rlang::last_error()
<error/dplyr:::mutate_error>
Error in `mutate()`:
ℹ In argument: `trend_data = list(...)`.
ℹ In row 212.
Caused by error:
! Cannot parse the supplied time format.
---
Backtrace:
  1. trendecon::proc_keyword_init("crypto", geo = "", from = "2014-01-01")
 13. trendecon::ts_gtrends(...)
 15. base::lapply(...)
 16. trendecon (local) FUN(X[[i]], ...)
 17. trendecon:::gtrends_with_backoff(...)
 18. base::tryCatch(...)
 19. base (local) tryCatchList(expr, classes, parentenv, handlers)
 20. base (local) tryCatchOne(expr, names, parentenv, handlers[[1L]])
 21. value[[3L]](cond)
 22. base::stop(e)
Run `rlang::last_trace()` to see the full context.
```

**Comment by karoliskoncevicius** [comment] 2023-02-25 21:25
So the error occurred when downloading 2022-09-01 : 2023-02-26 .

Do you know if you get the same error for any other keywords (maybe all of them?) Or just when downloading "crypto" ?

**Comment by tasfiq13** [comment] 2023-02-25 21:30
is is possible to set the end data? in my time zone its already 26 but its not 26 in many places. BTW same error for all keyword

**Comment by karoliskoncevicius** [comment] 2023-02-25 21:32
OK I am beginning to suspect where the issue is. In my location the date is still 2023-02-25 so the last daily date is 02-25:

![Screenshot 1](https://user-images.githubusercontent.com/7273684/221380526-198f69e0-a524-438a-87e1-3a271ff14448.png)

And in your place it's probably already 02-26? When I try to run `gtrends()` with that date I also get the same error:

    > gtrends("crypto", time="2022-09-01 2023-02-26")                                                                                                                                                       
    Error: Cannot parse the supplied time format.

Can you show the output of `Sys.time()` ?

**Comment by tasfiq13** [comment] 2023-02-25 21:33
Yeah maybe this is the issue. the output is

```
> Sys.time()
[1] "2023-02-26 05:33:18 +08"
```

**Comment by karoliskoncevicius** [comment] 2023-02-25 21:44
OK. In 20 minutes it's 2023-02-26 at my place. Will see if I get the same error then.

**Comment by karoliskoncevicius** [comment] 2023-02-25 22:03
I can reproduce the error.

**Comment by karoliskoncevicius** [comment] 2023-02-25 22:33
@tasfiq13 the issue should now e fixed in a development branch. If you want to update right away you can install it by calling:

    remotes::install_github("trendecon/trendecon@dev86")

Later, after internal review we will merge it into master.

**Comment by tasfiq13** [comment] 2023-02-26 09:40
Thanks a lot for fixing the bug. It works perfectly now.

**Closed** 2023-02-26 09:41 UTC
Labels: bug
